elevation_mapping:
  ros__parameters:
    min_update_rate: 5.0
    time_tolerance: 0.5
    sensor_processor/ignore_points_above: 0.65
    robot_motion_map_update/covariance_scale_translation_x: 0.0
    robot_motion_map_update/covariance_scale_translation_y: 0.0
    robot_motion_map_update/covariance_scale_translation_z: 0.0
    robot_motion_map_update/covariance_scale_rotation_x: 0.0
    robot_motion_map_update/covariance_scale_rotation_y: 0.0
    robot_motion_map_update/covariance_scale_rotation_z: 0.0

    length_in_x: 6.0
    length_in_y: 6.0
    position_x: 0.0
    position_y: 0.0
    resolution: 0.1
    min_variance: 0.0001
    max_variance: 0.05
    mahalanobis_distance_threshold: 2.5
    multi_height_noise: 0.001
    fused_map_publishing_rate: 5.0
    enable_visibility_cleanup: false
    visibility_cleanup_rate: 1.0
    scanning_duration: 0.1
